myproject/core/views.py
from flask import render_template, request, Blueprint, redirect, url_for, flash
from myproject.models import Movie
from myproject import db
from myproject.core.forms import SendEmailForm
import smtplib
from flask_login import current_user


core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get(1, type=int)
    movie_posts = Movie.query.order_by(Movie.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html', movie_posts=movie_posts)


@core.route('/about')
def about():
    return render_template('about.html')


@core.route('/<int:movie_id>/send', methods=['POST', 'GET'])
def send_email(movie_id):
    movie = Movie.query.get_or_404(movie_id)
    form = SendEmailForm()

    if form.validate_on_submit():
        sender_email = form.sender_email.data
        receiver_email = form.receiver_email.data
        password = form.password.data
        subject = form.subject.data
        body = f"Hey buddy,\n\nHere is an amazing movie you must watch,\n{movie.name}\nGenre: {movie.genre}\nStarring{movie.cast}\n\nEnjoy!"
        message = f'Subject: {subject}\n\n{body}'
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message)
        flash('Email sent successfully')
        return redirect(url_for('core.index'))
    elif request.method == 'GET':
        form.subject.data = "Hey, don't forget to watch this movie"
        form.body.data = f"Hey buddy,\n\nHere is an amazing movie you must watch,\n{movie.name}\nGenre: {movie.genre}\nStarring{movie.cast}\n\nEnjoy!!"
    return render_template('sending_email.html', form=form)

myproject/movies/views.py
from os import abort

from flask import url_for, redirect, render_template, request, Blueprint, flash
from myproject import db
from myproject.models import Movie, User
from myproject.movies.forms import AddMovieForm, SearchMovieForm
from flask_login import current_user, login_required
from sqlalchemy import join
from sqlalchemy import or_
from sqlalchemy.sql import select

movie = Blueprint('movie', __name__)


@movie.route('/add_movie', methods=['GET', 'POST'])
def add_movie():
    form = AddMovieForm()

    if form.validate_on_submit():
        new_movie = Movie(name=form.name.data, cast=form.cast.data,
                          genre=form.genre.data, rating=form.rating.data,
                          review=form.comment.data, user_id=current_user.id)
        db.session.add(new_movie)
        db.session.commit()
        db.session.flush()
        # movie_id = new_movie.id
        # user_id = current_user.id
        # new_post = Post(user_id=user_id, movie_id=movie_id)
        # db.session.add(new_post)
        # db.session.commit()
        return redirect(url_for('core.index'))

    return render_template('add_movie.html', form=form)


@movie.route('/<int:movie_id>')
def movie_post(movie_id):

    post_movie = Movie.query.get_or_404(movie_id)
    return render_template('movie_post.html', post=post_movie, name=post_movie.name,
                           cast=post_movie.cast, genre=post_movie.genre,
                           review=post_movie.review, rating=post_movie.rating)


@movie.route('/<int:movie_id>/delete', methods=['POST'])
@login_required
def delete_post(movie_id):
    post_movie = Movie.query.get_or_404(movie_id)
    if post_movie.audience != current_user:
        abort(403)
    db.session.delete(post_movie)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))


@movie.route('/<int:movie_id>/update', methods=['GET','POST'])
@login_required
def update(movie_id):
    post_movie = Movie.query.get_or_404(movie_id)
    if post_movie.audience != current_user:
        abort(403)
    form = AddMovieForm()
    if form.validate_on_submit():
        post_movie.name = form.name.data
        post_movie.cast = form.cast.data
        post_movie.review = form.comment.data
        post_movie.rating = form.rating.data
        post_movie.genre = form.genre.data
        db.session.commit()
        flash("Post Updated")
        return redirect(url_for('movie.movie_post', movie_id=post_movie.id))
    elif request.method == 'GET':
        form.name.data = post_movie.name
        form.cast.data = post_movie.cast
        form.comment.data = post_movie.review
        form.rating.data = post_movie.rating
        form.genre.data = post_movie.genre
    return render_template('add_movie.html', form=form)


@movie.route('/search_movies', methods=['GET', 'POST'])
def search_movies():
    searched_movie_data = Movie.query.all()
    searched_movie_data_dict = enumerate(searched_movie_data, start=1)
    return render_template('show.html', R=searched_movie_data_dict)

myproject/users/views.py
from flask import render_template, url_for, redirect, request, Blueprint, flash
from flask_login import login_user, login_required, current_user, logout_user
from myproject import db
from myproject.models import User, Movie
from myproject.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from myproject.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

# Register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(name=form.name.data, email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        flash("Thanks for registration")
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)

# Login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash("Login success")

            next = request.args.get('next')

            if next is None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)

# Logout
@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

# Account
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Profile Updated")
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.name.data = current_user.name
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


# Posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    movie_posts = Movie.query.filter_by(audience=user).order_by(Movie.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_movie_posts.html', movie_posts=movie_posts, user=user)

myproject/templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <h1>ETR</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
        ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>


{% endblock %}

myproject/templates/account.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <div align="center">
        <h1>Welcome to the account page for {{ current_user.username }}</h1>
        <img src="{{ url_for('static', filename='profile_pics/'+current_user.profile_image) }}" align="center">
    </div>
</div>
<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
        {{ form.name.label(class="form-group") }} {{ form.name(class="form-control") }}
        </div>
        <div class="form-group">
        {{ form.username.label(class="form-group") }} {{ form.username(class="form-control") }}
        </div>
        <div class="form-group">
        {{ form.email.label(class="form-group") }} {{ form.email(class="form-control") }}
        </div>
        <div class="form-group">
        {{ form.picture.label(class="form-group") }} {{ form.picture(class="form-control") }}
        </div>
        <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>

</div>

{% endblock %}

myproject/templates/add_movie.html
{% extends 'base.html' %}


{% block content %}

<div class="jumbotron" align="center">
    <form method="post">
        {{ form.hidden_tag() }}
        <table>
            <tr>
                <td>
                    {{ form.name.label }}
                </td>
                <td>
                    {{ form.name }}
                </td>
            </tr>
            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.cast.label }}
                </td>
                <td>
                    {{ form.cast }}
                </td>
            </tr>
            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.genre.label }}
                </td>
                <td>
                    {{ form.genre }}
                </td>
            </tr>
            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.rating.label }}
                </td>
                <td>
                    {{ form.rating }}
                </td>
            </tr>
            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.comment.label}}
                </td>
                <td>
                    {{ form.comment(style="min-width:187px" )}}
                </td>
            </tr>
            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    {{ form.submit() }}
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ETR</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </head>
  <body>
  <nav class="navbar sticky-top navbar-dark bg-dark">
      <ul class="nav">
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Home</a>
        </li>

        <li class="nav-link">
            <a href="{{ url_for('core.about') }}">About</a>
        </li>
        {% if current_user.is_authenticated %}

        <li class="nav-link">
            <a href="{{ url_for('users.logout') }}">Logout</a>
        </li>

        <li class="nav-link">
            <a href="{{ url_for('users.account') }}">Account</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Create Post</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('movie.add_movie') }}">Movie</a>
              <a class="dropdown-item" href="#">Song</a>
              <a class="dropdown-item" href="#">Show</a>
            </div>
        </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Search</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{{ url_for('movie.search_movies') }}">Movie</a>
              <a class="dropdown-item" href="#">Song</a>
              <a class="dropdown-item" href="#">Show</a>
            </div>
        </li>

        {% else %}
        <li class="nav-link">
            <a href="{{ url_for('users.login') }}">Login</a>
        </li>

        <li class="nav-link">
            <a href="{{ url_for('users.register') }}">Register</a>
        </li>
        {% endif %}
    </ul>
  </nav>


  {% block content %}


  {% endblock %}
  </body>
</html>

myproject/templates/index.html
{% extends 'base.html' %}

{% block content %}
 <div class="jumbotron">
    <h1>Entertainment To Remember</h1>
    <p>Welcome To The World Of Entertainment</p>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in movie_posts.items %}

    <div class="card" >
      <div class="card-body">
        <h2>
            <a class="card-title"  href="  {{ url_for('movie.movie_post', movie_id=post.id) }}">
                {{ post.name }}
            </a>
        </h2>
        <a style="text-decoration: none;color: black" href="{{ url_for('users.user_posts', username=post.audience.username) }}">
            Posted By: {{ post.audience.username }}
        </a>
        <p>
            Posted on: {{ post.date.strftime('%Y-%m-%d') }}
        </p>
          <!--
        <p>
            Genre: {{ post.genre }}
        </p>
        <p>
            I'm rating this movie: {{ post.rating }}
        </p>
        <p>
            Cast: {{ post.cast }}
        </p>
        -->
        <p class="card-text">
            {{ post.review[:10] }}...
        </p>
        <a href="{{ url_for('movie.movie_post', movie_id=post.id) }}" class="btn btn-primary">
            Read Complete Post
        </a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in movie_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if movie_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
     </ul>
   </nav>
  </div>

{% endblock %}

myproject/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid" align="center">
    <div class="jumbotron">
        <form method="post">
            {{ form.hidden_tag() }}
            <table>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.email.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.email }}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.password.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.password }}
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="">
                            {{ form.submit(class='btn btn-primary') }}
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>


{% endblock %}

myproject/templates/movie_post.html
{% extends 'base.html' %}

{% block content%}

<div class="jumbotron" align="center">
    <h1>{{ post.title }}</h1>
    <h2>Posted by: {{ post.audience.username }}</h2>
    <h3>Posted On: {{ post.date.strftime('%B %d, %Y') }}</h3>
    <p>
        Genre: {{ post.genre }}
    </p>
    <p>
        I'm rating this movie: {{ post.rating }}
    </p>
    <p>
        Cast: {{ post.cast }}
    </p>
    <p> Comments {{post.review}}</p>
    {% if post.audience == current_user %}
    <div>
        <a class="btn btn-secondary" href="{{ url_for('movie.update', movie_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
        <a class="btn btn-secondary" href="{{ url_for('core.send_email', movie_id=post.id) }}">Share</a>
    </div>
    {% endif %}
</div>


<!-- Modal for Pop Up-->
{# https://getbootstrap.com/docs/4.1/components/modal/ #}
{# Notice how the link with the id to the button above! #}
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Post Pop up Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this post?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                <form action="{{ url_for('movie.delete_post', movie_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myproject/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron" align="center">
    <form method="post">
        {{ form.hidden_tag() }}
        <table>
            <tr>
                <td>
                    {{ form.email.label }}
                </td>
                <td>
                    {{ form.email }}
                </td>
            </tr>

            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.name.label }}
                </td>
                <td>
                    {{ form.name }}
                </td>
            </tr>

            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.username.label }}
                </td>
                <td>
                    {{ form.username }}
                </td>
            </tr>

            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.password.label }}
                </td>
                <td>
                    {{ form.password }}
                </td>
            </tr>

            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.pass_confirm.label }}
                </td>
                <td>
                    {{ form.pass_confirm }}
                </td>
            </tr>

            <tr>
                <td>
                   <p style="visibility: hidden;font-size: 5px">s</p>
                </td>
            </tr>
            <tr>
                <td>

                </td>
                <td>
                    {{ form.submit(class="btn btn-primary") }}
                </td>
            </tr>
        </table>
    </form>

</div>


{% endblock %}

myproject/templates/search_movie.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {{ form.hidden_tag() }}
    <div class="container">
        <div class="jumbotron">
            <table>
                <tr>
                    <td>
                        {{ form.name.label }}
                    </td>
                    <td>
                        {{ form.name }}
                    </td>
                </tr>
                <tr>
                    <td>
                        {{ form.cast.label }}
                    </td>
                    <td>
                        {{ form.cast }}
                    </td>
                </tr>
                <tr>
                    <td>
                        {{ form.genre.label }}
                    </td>
                    <td>
                        {{ form.genre}}
                    </td>
                </tr>
                <tr>
                    <td>
                        {{ form.submit(class='btn btn-primary') }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</form>

{% endblock %}

myproject/templates/search_results.html
{% extends 'base.html' %}

{% block content %}

{% for movie in movie_details %}

{% if current_user.id == movie.user_id%}
<h1> Movie Name :- {{ movie.name }}</h1>
<h1> Posted Date :- {{ movie.date }}</h1>
<h1> Movie Cast {{ movie.cast }}</h1>
<h1> Movie Rating :- {{ movie.rating }}</h1>
{% endif %}
{% endfor %}

{% endblock %}

myproject/templates/sending_email.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron" align="center">
        <form method="post">
            {{ form.hidden_tag() }}
            <table style="align-content: center">
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.sender_email.label }}<br>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.sender_email(placeholder="Enter your valid email(Google)", width="200px", class="form-control") }}
                        </div>
                    </td>
                </tr>
                <tr style="height: 3px">

                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.password.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.password(style="width:270px", class="form-control",placeholder="Enter Your Gmail Account Password") }}
                        </div>
                    </td>
                </tr>

            <tr style="height: 3px">


            </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.receiver_email.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.receiver_email(placeholder="Enter you friend''s valid email(Google)", class="form-control") }}
                        </div>
                    </td>
                </tr>

                <tr style="height: 3px">

                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.subject.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.subject(style="width:270px", class="form-control") }}
                        </div>
                    </td>
                </tr>

            <tr style="height: 3px">

            </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.body.label }}
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            {{ form.body(style="min-width:270px;min-height:200px;width:250px", class="form-control") }}
                        </div>
                    </td>
                </tr>
            <tr style="height: 3px">

            </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            {{ form.submit(class='btn btn-primary') }}
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>

</div>

{% endblock %}

myproject/templates/show.html
{% extends 'base.html' %}

{% block content %}

<script src="../static/Resources jQuery And CSS/jquery.min.js"></script>
<script src="../static/Resources jQuery And CSS/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="../static/Resources jQuery And CSS/jquery.dataTables.min.css">
<!--
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css"></link>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script src="http://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script> -->
<script src="https://use.fontawesome.com/94a96f108e.js"></script>

<script type="text/javascript">
    $(document).ready( function () {
    $('#AllPostedReview').DataTable({
         language: {
            searchPlaceholder: "Name, Cast, Genre, Rating"
        }
    });
    $(document).ready(function() {
    var dataTable = $('#AllPostedReview').dataTable();
    $("#searchbox").keyup(function() {
        dataTable.fnFilter(this.value);
    });
});

} );
</script>
<style type="text/css">
    .dataTables_filter {
     display: none;
}
</style>
<div class="container">
    <div class="jumbotron">
        <div class="form-group" style="width: 50%;">
            <input type="text" id="searchbox" class="form-control" align="center" placeholder="Enter Name, Cast, Review, Rating, Date Posted">
        </div>

    <table id="AllPostedReview" class="display">
    <thead>
        <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Cast</th>
            <th>Genre</th>
            <th>Rating</th>
            <th>Posted Date</th>
            <th style="max-width: 100px">Comment</th>
            <th>View Full Post</th>
            <th>Share</th>
        </tr>
    </thead>
    <tbody>
        {% for index, Result in R: %}
            <tr>
                <td>{{ index }}</td>
                <td>{{ Result.name }}</td>
                <td> {{ Result.cast }}</td>
                <td>{{ Result.genre}}</td>
                <td> {{ Result.rating }}</td>
                <td style="max-width: 100px">{{ Result.review }}</td>
                <td> {{ Result.date.strftime('%Y-%m-%d') }}</td>
                <td>
                    <a href="{{ url_for('movie.movie_post', movie_id=Result.id) }}" >
                        <i class="fa fa-info" aria-hidden="true"></i>
                    </a>
                </td>
                <td>
                    <a href="{{ url_for('core.send_email', movie_id=Result.id) }}" style="text-decoration: none;color: black">
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
    </div>
</div>

{% endblock %}

myproject/templates/user_movie_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align='center'>
            <h1>Welcome to the page for {{user.username}}</h1>
            <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
        </div>
    </div>


    {% for post in movie_posts.items %}

    <h2><a href="{{ url_for('movie.movie_post', movie_id=post.id) }}">{{ post.name }}</a></h2>
    Posted by: <a href="{{ url_for('users.user_posts', username=post.audience.username) }}">{{ post.audience.username
    }}</a>
    <p>Genre: {{ post.genre }}</p>
    <p>I'm rating this movie: {{ post.rating }}</p>
    <p>Cast: {{ post.cast }}</p>
        <br>
    <p>{{post.review}}</p>
    <br>
    <p class="text-muted">Posted on: {{ post.date.strftime('%Y-%m-%d') }}</p>


    {% endfor %}


</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {# http://flask.pocoo.org/snippets/44/ #}

        {% for page_num in movie_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if movie_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
                page_num }}</a></li>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link"
                                 href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
            page_num }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endblock content %}